apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    name: <P_NAME>
spec:
    replicas: 2
    strategy:
        rollingUpdate:
            maxSurge: 1
            maxUnavailable: 1
    template:
        metadata:
            labels:
                name: <P_NAME>
        spec:
            imagePullSecrets:
                - name: registry-secret
            containers:
                - name: <P_NAME>
                  image: <IMAGE_TAG>
                  imagePullPolicy: Always
                  ports:
                      - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
    name: <P_NAME>-service
spec:
    type: NodePort
    ports:
        - port: 80
          nodePort: 32070
    selector:
        name: <P_NAME>
